import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";
import Dummy from "@/components/dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/sc.js" strategy="lazyOnload"></Script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blog</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      {/* <Dummy /> */}
      <main className={styles.heroSection}>
        <div className={styles.heroSectionHeader}>
          <h1>Hunting Coder</h1>
          <p>A blog for hunting coders by a hunting coder</p>
        </div>
        <div>
          <div className="blogItem">
            <h1>How to learn Javascript in 2023</h1>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h1>How to learn Javascript in 2023</h1>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h1>How to learn Javascript in 2023</h1>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  );
}
