import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import Image from "next/image";
import heroImage from "../public/hero-image.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <style>
          {`
            h2{
              font-size:38px;
            }
            h3{
              font-size:28px;
            }

          `}
        </style>
        <div className={styles.heroSectionHeader}>
          <h1>Hunting Coder</h1>
          <p>A blog for hunting coders by a hunting coder</p>
        </div>
        <div className={styles.imageWrap}>
          <Image
            src={heroImage}
            alt="hero section"
            className={styles.heroImage}
          />
        </div>
        <div>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn Javascript in 2023</h3>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn Javascript in 2023</h3>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn Javascript in 2023</h3>
            <p>Javascript is the language use to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  );
}
